targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/_generated/{{}}.g.dart'
      json_serializable:
        options:
          explicit_to_json: true
          any_map: true
        generate_for:
          exclude:
            - 'lib/database/**'
      freezed|freezed:
        enabled: true
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/_generated/{{}}.freezed.dart'
      retrofit_generator:
        options:
          format_output: false